### ISSUE TITLE
bug: checkhealth causes crash

### ISSUE THREAD

**Issue by tris203** [folke/noice.nvim#996]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

Nightly

### Operating system/version

Ubuntu 22.04

### Describe the bug

nvim segfaults and returns to the command line

### Steps To Reproduce

1. run `:checkhealth vim.lsp`
2. with that still open run `:checkhealth vim.deprecated`
3. Observe crash

Alternatively
Run `:checkhealth noice` twice

### Expected Behavior

No crash

This doesnt happen with nvim --clean and doesn't happen if you `:bd` to close the existing tab first

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
  },
})
```

**Comment by folke** [comment]
Noice doesn't do anything with `:checkhealth`. Also, whenever Neovim crashes, that's due to bugs in NEovim.

Full stacktrace:

```c
Program terminated with signal SIGSEGV, Segmentation fault.
#0  frame2win (frp=frp@entry=0x0) at /home/runner/work/neovim/neovim/src/nvim/window.c:3474
[Current thread is 1 (Thread 0x7ec9ca4b6740 (LWP 3076343))]
#0  frame2win (frp=frp@entry=0x0) at /home/runner/work/neovim/neovim/src/nvim/window.c:3474
#1  0x00005dc023a13029 in winframe_find_altwin (win=win@entry=0x5dc03638fd40, dirp=dirp@entry=0x7fffa8cde05c, tp=tp@entry=0x5dc0363b36d0, altfr=altfr@entry=0x7fffa8cddfe0) at /home/runner/work/neovim/neovim/src/nvim/window.c:3211
#2  0x00005dc023a14c56 in winframe_remove (win=win@entry=0x5dc03638fd40, dirp=0x7fffa8cde05c, tp=tp@entry=0x5dc0363b36d0, unflat_altfr=unflat_altfr@entry=0x0) at /home/runner/work/neovim/neovim/src/nvim/window.c:3148
#3  0x00005dc023a17800 in win_free_mem (win=win@entry=0x5dc03638fd40, dirp=dirp@entry=0x7fffa8cde05c, tp=tp@entry=0x5dc0363b36d0) at /home/runner/work/neovim/neovim/src/nvim/window.c:3072
#4  0x00005dc023a17a8a in win_close_othertab (win=win@entry=0x5dc03638fd40, free_buf=free_buf@entry=0, tp=tp@entry=0x5dc0363b36d0) at /home/runner/work/neovim/neovim/src/nvim/window.c:3050
#5  0x00005dc023a1b0bf in close_windows (buf=0x5dc03623af70, keep_curwin=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/window.c:2510
#6  0x00005dc0237d4b93 in do_buffer_ext (action=action@entry=4, start=start@entry=1, dir=dir@entry=1, count=<optimized out>, count@entry=24, flags=flags@entry=0) at /home/runner/work/neovim/neovim/src/nvim/buffer.c:1401
#7  0x00005dc0237d500d in do_buffer (action=action@entry=4, start=start@entry=1, dir=dir@entry=1, count=count@entry=24, forceit=forceit@entry=0) at /home/runner/work/neovim/neovim/src/nvim/buffer.c:1582
#8  0x00005dc0237d50a8 in do_bufdel (command=4, arg=<optimized out>, addr_count=1, start_bnr=<optimized out>, end_bnr=24, forceit=0) at /home/runner/work/neovim/neovim/src/nvim/buffer.c:1100
#9  0x00005dc0238673fe in ex_bunload (eap=0x7fffa8cde920) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:4494
#10 0x00005dc02385eaf0 in execute_cmd0 (retv=retv@entry=0x7fffa8cde244, eap=eap@entry=0x7fffa8cde920, errormsg=errormsg@entry=0x7fffa8cde248, preview=preview@entry=false) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:1714
#11 0x00005dc02385f155 in execute_cmd (eap=0x7fffa8cde920, cmdinfo=<optimized out>, preview=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:1796
#12 0x00005dc02379a88c in nvim_cmd (channel_id=9223372036854775809, cmd=<optimized out>, opts=0x7fffa8cdebb7, arena=0x7fffa8cdebd0, err=0x7fffa8cdebc0) at /home/runner/work/neovim/neovim/src/nvim/api/command.c:646
#13 0x00005dc0238b5c35 in nlua_api_nvim_cmd (lstate=0x7ec9ca7f3380) at /home/runner/work/neovim/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.h:1780
#14 0x00005dc023a9dc66 in lj_BC_FUNCC ()
#15 0x00005dc023a89e96 in lua_pcall (L=L@entry=0x7ec9ca7f3380, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=-4) at lj_api.c:1122
#16 0x00005dc0238c5c95 in nlua_pcall (lstate=0x7ec9ca7f3380, nargs=2, nresults=1) at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:174
#17 0x00005dc0238d2cb8 in nlua_exec (str=..., args=..., mode=kRetNilBool, arena=0x0, err=0x7fffa8cdee70) at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:1561
#18 0x00005dc02386d224 in ex_checkhealth (eap=0x7fffa8cdf380) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:7694
#19 0x00005dc02385eaf0 in execute_cmd0 (retv=retv@entry=0x7fffa8cdf374, eap=eap@entry=0x7fffa8cdf380, errormsg=errormsg@entry=0x7fffa8cdf378, preview=preview@entry=false) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:1714
#20 0x00005dc0238600a9 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fffa8cdf5c8, flags=flags@entry=0, cstack=cstack@entry=0x7fffa8cdf650, fgetline=fgetline@entry=0x5dc0238752ab <getexline>, cookie=cookie@entry=0x0) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2358
#21 0x00005dc023860df2 in do_cmdline (cmdline=<optimized out>, fgetline=0x5dc0238752ab <getexline>, cookie=0x0, flags=0) at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:667
#22 0x00005dc02392187f in nv_colon (cap=0x7fffa8cdfc70) at /home/runner/work/neovim/neovim/src/nvim/normal.c:3191
#23 0x00005dc02391b968 in normal_execute (state=0x7fffa8cdfc00, key=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/normal.c:1243
#24 0x00005dc0239bf4f4 in state_enter (s=0x7fffa8cdfc00) at /home/runner/work/neovim/neovim/src/nvim/state.c:102
#25 0x00005dc02391a2de in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/normal.c:521
#26 0x00005dc0238d9442 in main (argc=2, argv=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/main.c:660
```
